use_frameworks!

target 'SDDateHelper_Example' do
  pod 'SDDateHelper', :path => '../'
  
  target 'SDDateHelper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
